# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [6]:
Version=np.__version__

print ("""
Version : %s\n
Config  : %s
""" %(Version,np.show_config()))

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/P

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

<function numpy.core.fromnumeric.size(a, axis=None)>

In [18]:
arr=np.arange(9).reshape(3,3)

In [19]:
arr.size

9

In [20]:
arr.itemsize

4

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [25]:
np.info(arr)

class:  ndarray
shape:  (3, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x14d9e6f5ec0
byteorder:  little
byteswap:  False
type: int32


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [27]:
zarr=np.zeros(10)
zarr[4]=1
zarr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [28]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [29]:
np.arange(9)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [32]:
np.arange(9).reshape(3,3,)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [34]:
nz=[1,2,0,0,4,0]


In [35]:
np.nonzero(nz)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [36]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [42]:
np.random.random(27).reshape(3,3,3)

array([[[0.89786981, 0.00574372, 0.07882532],
        [0.76987241, 0.36310772, 0.32026836],
        [0.00327213, 0.01912285, 0.83629225]],

       [[0.66428229, 0.37076869, 0.91178336],
        [0.76485861, 0.37204669, 0.30102405],
        [0.74825096, 0.70377887, 0.57253035]],

       [[0.12932656, 0.16427573, 0.58645761],
        [0.59089538, 0.73676957, 0.89255388],
        [0.56371148, 0.33045379, 0.46251173]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [45]:
arr1=np.arange(100).reshape(10,10) ; arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
arr1.min()

0

In [48]:
arr1.max()

99

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [50]:
arr2=np.arange(30)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
arr2.mean()

14.5

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [64]:
arr3=np.ones(18).reshape(6,3);arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
arr3[1:-1, 1:-1]=0
arr3

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [68]:
arr3=np.ones(18).reshape(6,3);arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
np.pad(arr3,(6,3),'constant')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [75]:
0 * np.nan

nan

In [76]:
np.nan == np.nan

False

In [77]:
np.inf > np.nan

False

In [78]:
np.nan - np.nan

nan

In [79]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [91]:
arr4=np.arange(25).reshape(5,5) ; arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
np.diag(np.diag(arr4))/6

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [98]:
arr5=np.arange(64).reshape(8,8);arr5[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [100]:
arr5[::-2]

array([[56, 57, 58, 59, 60, 61, 62, 63],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [101]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [103]:
np.tile(arr5,(8,8))

array([[ 0,  1,  2, ...,  5,  6,  7],
       [ 8,  9, 10, ..., 13, 14, 15],
       [16, 17, 18, ..., 21, 22, 23],
       ...,
       [40, 41, 42, ..., 45, 46, 47],
       [48, 49, 50, ..., 53, 54, 55],
       [56, 57, 58, ..., 61, 62, 63]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [107]:
x=np.random.random(25).reshape(5,5)

In [111]:
(x - x.min()) / (x.max() - x.min())

array([[7.64704775e-01, 8.16059528e-01, 2.42983685e-01, 3.34635043e-01,
        5.30983482e-02],
       [3.33433872e-01, 4.96542120e-01, 9.29361839e-04, 8.42938280e-01,
        4.52034625e-01],
       [1.25181504e-01, 9.85557738e-01, 6.47032731e-01, 2.26703881e-01,
        2.78909024e-01],
       [2.10264210e-01, 3.24818259e-01, 5.45294869e-01, 1.28346553e-01,
        1.26183831e-01],
       [6.67435357e-02, 0.00000000e+00, 8.38759704e-01, 1.00000000e+00,
        1.25654254e-02]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [116]:
byte=np.ubyte
np.dtype([("r", byte, 1),
                  ("g", byte, 1),
                  ("b", byte, 1),
                  ("a", byte, 1)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [118]:
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)

In [119]:
np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [121]:
x=np.arange(15)
x[(x>3) & (x<=8)]

array([4, 5, 6, 7, 8])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [122]:
print(sum(range(5),-1))

9


In [123]:
from numpy import *
print(sum(range(5),-1))

10


In [124]:
np.sum(range(5),-1)

10

In [125]:
range(5)

range(0, 5)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [127]:
Z=np.arange(3);Z

array([0, 1, 2])

In [130]:
sq=Z**Z
st=2 << Z >> 2
ls=Z <- Z
comp=1j*Z
divdiv=Z/1/1
#cond=Z<Z>Z

print("""
%s
%s
%s
%s
%s
%s
""" %(sq,st,ls,comp,divdiv,5))


[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]
5



In [136]:
import sys
try:
    Z<Z>Z
except:
    print(sys.exc_info())

(<class 'ValueError'>, ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',), <traceback object at 0x0000014D9EC1ED48>)


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [137]:
np.array(0) / np.array(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [138]:
np.array(0) // np.array(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [139]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [140]:
np.random.uniform(-10,+10,10)

array([ 2.73090873, -9.80298818, -4.99614014, -3.15744625,  8.63202566,
       -9.61512303,  3.73612707, -2.09376092,  2.88078201,  6.79122015])

In [141]:
np.copysign(np.ceil(np.abs(x)), x) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [142]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [146]:
a=np.arange(0,25)
b=np.arange(10,35)
np.intersect1d(a,b)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [153]:
defaults=np.seterr(all="ignore")
X=np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [154]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [156]:
np.datetime64('today','D')

numpy.datetime64('2018-11-04')

In [157]:
np.datetime64('today','D') - 1

numpy.datetime64('2018-11-03')

In [158]:
np.datetime64('today','D') + 1

numpy.datetime64('2018-11-05')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [163]:
np.arange('2018-07','2018-08', dtype='datetime64[D]')

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [178]:
A=np.array([1,2,3])
B=np.array([4,5,6])
Add=np.add(A,B, out=B) 
Div=np.divide(A, 2) 
Neg=np.negative(Div,out=Div) 
#(A+B)*(-A/2)

Mult=np.multiply(Add,Neg, out=Neg)
Mult

array([ -2.5,  -7. , -13.5])

In [174]:
A=np.array([1,2,3]) ;np.divide(A, 2)

array([0.5, 1. , 1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [8]:
randarr=np.random.uniform(0,10,10)
mod=randarr - randarr%1
floor=np.floor(randarr)
ceil=np.ceil(randarr)-1
astype=randarr.astype(int)
trunc=np.trunc(randarr)


print("""
Random Array : %s
Modulus      : %s
Floor        : %s
Ceil         : %s
astype       : %s
Trunc        : %s
""" %(randarr,mod,floor,ceil,astype,trunc))


Random Array : [6.89356701 0.67266593 2.39482762 4.21582775 3.10643763 4.54579907
 9.86592012 1.46759067 5.6314758  1.01596555]
Modulus      : [6. 0. 2. 4. 3. 4. 9. 1. 5. 1.]
Floor        : [6. 0. 2. 4. 3. 4. 9. 1. 5. 1.]
Ceil         : [6. 0. 2. 4. 3. 4. 9. 1. 5. 1.]
astype       : [6 0 2 4 3 4 9 1 5 1]
Trunc        : [6. 0. 2. 4. 3. 4. 9. 1. 5. 1.]



#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [15]:
M=np.zeros((5,5));M

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
M+=np.arange(5);M

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [24]:
def generate():
    for x in range(10):
        yield x

Gen=np.fromiter(generate(),dtype=float,count=-1)
print(Gen)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [26]:
np.linspace(0,1)[1:-1]

array([0.02040816, 0.04081633, 0.06122449, 0.08163265, 0.10204082,
       0.12244898, 0.14285714, 0.16326531, 0.18367347, 0.20408163,
       0.2244898 , 0.24489796, 0.26530612, 0.28571429, 0.30612245,
       0.32653061, 0.34693878, 0.36734694, 0.3877551 , 0.40816327,
       0.42857143, 0.44897959, 0.46938776, 0.48979592, 0.51020408,
       0.53061224, 0.55102041, 0.57142857, 0.59183673, 0.6122449 ,
       0.63265306, 0.65306122, 0.67346939, 0.69387755, 0.71428571,
       0.73469388, 0.75510204, 0.7755102 , 0.79591837, 0.81632653,
       0.83673469, 0.85714286, 0.87755102, 0.89795918, 0.91836735,
       0.93877551, 0.95918367, 0.97959184])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [27]:
Sort=np.random.random(10) ; Sort

array([0.30610288, 0.50922114, 0.97445282, 0.75079504, 0.13074686,
       0.63031308, 0.93652602, 0.74071903, 0.52495527, 0.86364523])

In [29]:
Sort.sort();Sort

array([0.13074686, 0.30610288, 0.50922114, 0.52495527, 0.63031308,
       0.74071903, 0.75079504, 0.86364523, 0.93652602, 0.97445282])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [30]:
arr=np.arange(10);arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
import time

In [35]:
# Time=time.now
# np.add.reduce(arr)
# (time.now - Time)*1000

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [36]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print("""
A : %s
B : %s
Eq: %s
""" %(A,B,equal))


A : [0 1 0 1 1]
B : [1 0 1 0 1]
Eq: False



#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [38]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [41]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print("""
Z : %s
X : %s
Y : %s
R : %s
T : %s
""" %(Z,X,Y,R,T))


Z : [[0.49038092 0.52383369]
 [0.3882109  0.8606929 ]
 [0.2432521  0.71773036]
 [0.82254954 0.35151351]
 [0.53879797 0.20419894]
 [0.1619727  0.15790719]
 [0.01309045 0.06621519]
 [0.53301327 0.89146792]
 [0.06556502 0.07381514]
 [0.15546648 0.02333708]]
X : [0.49038092 0.3882109  0.2432521  0.82254954 0.53879797 0.1619727
 0.01309045 0.53301327 0.06556502 0.15546648]
Y : [0.52383369 0.8606929  0.71773036 0.35151351 0.20419894 0.15790719
 0.06621519 0.89146792 0.07381514 0.02333708]
R : [0.71754803 0.94419276 0.75783142 0.89451076 0.57619481 0.2262075
 0.06749675 1.03866173 0.09872916 0.15720829]
T : [0.81837012 1.14707404 1.24402756 0.40385632 0.362264   0.77268935
 1.37561756 1.03191857 0.84452067 0.14899759]



#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [42]:
randarr

array([6.89356701, 0.67266593, 2.39482762, 4.21582775, 3.10643763,
       4.54579907, 9.86592012, 1.46759067, 5.6314758 , 1.01596555])

In [47]:
randarr[randarr.argmax()]=0; randarr

array([6.89356701, 0.67266593, 2.39482762, 4.21582775, 3.10643763,
       4.54579907, 0.        , 1.46759067, 5.6314758 , 1.01596555])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [48]:
coord=np.zeros((10,10),[('x',float),('y',float)])

In [49]:
coord['x'],coord['y']=np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))

In [50]:
print(coord)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [51]:
coord['x']

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.2222222

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [56]:
A=np.arange(8)
B=A+0.5
#C (Cij =1/(xi - yj))
C=np.subtract.outer(A,B)
print(C,"\n",np.linalg.det(C))

[[-0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5]
 [ 0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5]
 [ 1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5]
 [ 2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5]
 [ 3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5]
 [ 4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5]
 [ 5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5]
 [ 6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5]] 
 1.8457040860738383e-92


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [57]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [58]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


In [59]:
print(np.finfo(dtype).eps)

2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [60]:
np.set_printoptions(threshold=np.nan)
D = np.zeros((25,25))
print(D)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [62]:
Z = np.arange(100)
v = np.random.uniform(0,100)
absvalue=np.abs(Z-v)
index = (absvalue).argmin()
print("""
Z           : %s
v           : %s 
absvalue    : %s
index       : %s
final Zindex: %s
""" %(Z,v,absvalue,index,Z[index]))


Z           : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
v           : 48.90480601130533 
absvalue    : [48.90480601 47.90480601 46.90480601 45.90480601 44.90480601 43.90480601
 42.90480601 41.90480601 40.90480601 39.90480601 38.90480601 37.90480601
 36.90480601 35.90480601 34.90480601 33.90480601 32.90480601 31.90480601
 30.90480601 29.90480601 28.90480601 27.90480601 26.90480601 25.90480601
 24.90480601 23.90480601 22.90480601 21.90480601 20.90480601 19.90480601
 18.90480601 17.90480601 16.90480601 15.90480601 14.90480601 13.90480601
 12.90480601 11.90480601 10.90480601  9.90480601  8.90480601  7.90480601
  6.90480601  5.90480601  4.90480601  3.90480601  2.90480601  1.90480601
  0.90480601  0.09519399  1.09519399  2.09519399

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [63]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [65]:
A=np.random.random((10,2));A

array([[0.32254028, 0.41229336],
       [0.70039277, 0.29912792],
       [0.32350264, 0.27807934],
       [0.34845929, 0.8778416 ],
       [0.54628451, 0.74863728],
       [0.03293304, 0.95015041],
       [0.49046645, 0.35863094],
       [0.57584544, 0.74925371],
       [0.81833884, 0.76611871],
       [0.95649484, 0.13987991]])

In [66]:
X,Y=np.atleast_2d(A[:,0]),np.atleast_2d(A[:,1]) ;X,Y

(array([[0.32254028, 0.70039277, 0.32350264, 0.34845929, 0.54628451,
         0.03293304, 0.49046645, 0.57584544, 0.81833884, 0.95649484]]),
 array([[0.41229336, 0.29912792, 0.27807934, 0.8778416 , 0.74863728,
         0.95015041, 0.35863094, 0.74925371, 0.76611871, 0.13987991]]))

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [67]:
Z = np.arange(10, dtype=np.int32);Z
Z = Z.astype(np.float32, copy=False);Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [71]:

txt=np.genfromtxt('cities.csv',delimiter=',') ; txt

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 41.,   5.,  59.,  nan,  80.,  39.,   0.,  nan,  nan,  nan],
       [ 42.,  52.,  48.,  nan,  97.,  23.,  23.,  nan,  nan,  nan],
       [ 46.,  35.,  59.,  nan, 120.,  30.,  36.,  nan,  nan,  nan],
       [ 42.,  16.,  12.,  nan,  71.,  48.,   0.,  nan,  nan,  nan],
       [ 43.,  37.,  48.,  nan,  89.,  46.,  11.,  nan,  nan,  nan],
       [ 36.,   5.,  59.,  nan,  80.,  15.,   0.,  nan,  nan,  nan],
       [ 49.,  52.,  48.,  nan,  97.,   9.,   0.,  nan,  nan,  nan],
       [ 39.,  11.,  23.,  nan,  78.,   9.,  36.,  nan,  nan,  nan],
       [ 34.,  14.,  24.,  nan,  77.,  55.,  11.,  nan,  nan,  nan],
       [ 39.,  45.,   0.,  nan,  75.,  33.,   0.,  nan,  nan,  nan],
       [ 48.,   9.,   0.,  nan, 103.,  37.,  12.,  nan,  nan,  nan],
       [ 41.,  15.,   0.,  nan,  77.,   0.,   0.,  nan,  nan,  nan],
       [ 37.,  40.,  48.,  nan,  82.,  16.,  47.,  nan,  nan,  nan],
       [ 33.,  54.,   0.,  nan,  9

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [73]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [75]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)